dbpath=C:\Users\maria\PycharmProjects\Pisid_iscte\replica_dados_pisid\server1\data
logpath=C:\Users\maria\PycharmProjects\Pisid_iscte\replica_dados_pisid\server1\logs\mongo.log
port=27019
replSet=replicaimdb