dbpath=C:\Users\maria\OneDrive\Ambiente de Trabalho\3ANO\Pisid\replica_dados_pisid\server1\data
logpath=C:\Users\maria\OneDrive\Ambiente de Trabalho\3ANO\Pisid\replica_dados_pisid\server1\logs\mongo.log
port=27019
replSet=replicaimdb